[phases.setup]
nixPkgs = ["python310", "nodejs-18_x", "yarn"]

[phases.install]
cmds = [
    "pip install --user --upgrade pip setuptools wheel",
    "pip install --user -e .",
    "cd client && yarn install && yarn build"
]

[start]
cmd = "PATH=$HOME/.local/bin:$PATH gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers=2"

[variables]
PIP_BREAK_SYSTEM_PACKAGES = "1"

