[phases.setup]
nixPkgs = ["python310", "nodejs-18_x", "yarn", "gcc"]

[phases.install]
cmds = [
    "python -m ensurepip --upgrade",
    "python -m pip install --upgrade pip setuptools wheel",
    "python -m pip install -e .",
    "cd client && yarn install && yarn build"
]

[start]
cmd = "gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers=2"

